Repository mdx-js/mdx-analyzer, pull requests merged in 2023-12, with the labels that each got.

#357 Fix dropping local media in an MDX file
  .changeset/fix-drop-provider.md
  packages/vscode-mdx/src/document-drop-edit-provider.js
Labels: 🐛 type/bug, 🗄 area/interface, 👶 semver/patch, 👍 phase/yes

#358 Add a TypeScript version status item
  .changeset/ts-version-status-item.md
  packages/vscode-mdx/package.json
  packages/vscode-mdx/src/extension.js
Labels: 🦋 type/enhancement, 🗄 area/interface, 🧒 semver/minor, 👍 phase/yes

#364 Disable formatting
  .changeset/tasty-geckos-obey.md
  packages/language-service/lib/language-module.js
  packages/language-service/test/language-module.js
Labels: 🐛 type/bug, 🗄 area/interface, 🙆 yes/confirmed, 👍 phase/yes

#366 Enhance how the Props type is used
  .changeset/tame-moles-type.md
  packages/language-server/test/diagnostics.test.js
  packages/language-service/lib/language-module.js
  packages/language-service/test/language-module.js
Labels: 🦋 type/enhancement, 🗄 area/interface, 👶 semver/patch, 🤞 phase/open

#367 Fix the README title in the `language-server` package
  packages/language-server/README.md
Labels: 👋 phase/new

#365 Support MDX layout
  .changeset/purple-mice-rhyme.md
  package.json
  packages/language-service/lib/language-module.js
  packages/language-service/test/language-module.js
  packages/language-service/types.d.ts
Labels: 🐛 type/bug, 🗄 area/interface, 👶 semver/patch, 🙆 yes/confirmed, 👍 phase/yes

#370 Dedent virtual markdown chunks
  packages/language-service/lib/language-module.js
  packages/language-service/test/language-module.js
Labels: 🐛 type/bug, 🗄 area/interface, 👶 semver/patch, 👍 phase/yes

#368 Remove the language module dependency on TypeScript
  .changeset/purple-kings-unite.md
  packages/language-server/lib/language-server-plugin.js
  packages/language-service/lib/language-module.js
  packages/language-service/test/language-module.js
Labels: 🗄 area/interface, 💬 type/discussion, 🤞 phase/open

#375 Fix return type of MDXContent in case of syntax error
  .changeset/pink-beans-move.md
  packages/language-service/lib/virtual-file.js
  packages/language-service/test/language-module.js
Labels: 🐛 type/bug, 🗄 area/interface, 👶 semver/patch, 👍 phase/yes

#374 Handle MDX parse errors
  .changeset/loud-balloons-roll.md
  fixtures/node16/syntax-error.mdx
  packages/language-server/lib/language-server-plugin.js
  packages/language-server/test/completion.test.js
  packages/language-server/test/diagnostics.test.js
  packages/language-server/test/plugins.test.js
  packages/language-service/index.js
  packages/language-service/lib/language-plugin.js
  packages/language-service/lib/service-plugin.js
  packages/language-service/lib/virtual-file.js
  packages/language-service/package.json
  packages/language-service/test/language-module.js
Labels: 🦋 type/enhancement, 🗄 area/interface, 👶 semver/patch, 👍 phase/yes

#377 Support await expressions
  .changeset/odd-fireants-smell.md
  packages/language-service/lib/virtual-file.js
  packages/language-service/package.json
  packages/language-service/test/language-module.js
Labels: 🦋 type/enhancement, 🗄 area/interface, 👶 semver/patch, 👍 phase/yes

#380 docs: update some outdated links
  packages/vscode-mdx/README.md
Labels: 🤞 phase/open

#381 Leverage Volar’s document drop edits provider
  .changeset/ten-suns-hammer.md
  .changeset/twelve-cheetahs-occur.md
  packages/language-service/lib/service-plugin.js
  packages/language-service/package.json
  packages/vscode-mdx/package.json
  packages/vscode-mdx/src/document-drop-edit-provider.js
  packages/vscode-mdx/src/extension.js
Labels: 🦋 type/enhancement, 🏡 area/internal, 👶 semver/patch, 🙆 yes/confirmed, 👍 phase/yes

#383 Refactor loading remark plugins from tsconfig.json
  .changeset/afraid-dodos-rhyme.md
  packages/language-server/index.js
  packages/language-server/lib/configuration.js
  packages/language-service/index.js
  packages/language-service/lib/tsconfig.js
Labels: 🦋 type/enhancement, 🗄 area/interface, 🏡 area/internal, 👶 semver/patch, 👍 phase/yes

#382 Inject JSX comments into MDX
  packages/language-server/index.js
  packages/language-server/test/completion.test.js
  packages/language-service/lib/language-plugin.js
  packages/language-service/lib/virtual-file.js
  packages/language-service/test/language-module.js
Labels: 🦋 type/enhancement, 🏡 area/internal, 👶 semver/patch, 🤞 phase/open
