Repository mdx-js/mdx-analyzer, pull requests merged in 2023-10, with the labels that each got.

#344 Update to MDX 3
  .changeset/gorgeous-islands-camp.md
  packages/language-server/package.json
  packages/language-service/lib/language-module.js
  packages/language-service/package.json
Labels: 🦋 type/enhancement, 📦 area/deps, 👍 phase/yes

#345 Support to drag and drop images and text into MDX
  .changeset/lucky-books-tan.md
  packages/vscode-mdx/package.json
  packages/vscode-mdx/src/document-drop-edit-provider.js
  packages/vscode-mdx/src/extension.js
  packages/vscode-mdx/tsconfig.json
Labels: 🦋 type/enhancement, 🗄 area/interface, 👍 phase/yes

#347 fix: Push diagnostics from server
  packages/vscode-mdx/src/extension.js
Labels: 🦋 type/enhancement, 🗄 area/interface, 🧒 semver/minor, 👍 phase/yes
