Repository mdx-js/mdx-analyzer, pull requests merged in 2024-06, with the labels that each got.

#444 Document syntax highlighting for MDX code blocks
  .changeset/khaki-coats-press.md
  packages/vscode-mdx/README.md
Labels: 📚 area/docs, 🦋 type/enhancement, 👶 semver/patch, 👍 phase/yes

#448 Fix virtual code when JSX child starts with >
  .changeset/wild-kangaroos-travel.md
  packages/language-service/lib/virtual-code.js
  packages/language-service/test/language-plugin.js
Labels: 🐛 type/bug, 🗄 area/interface, 👶 semver/patch, 🙆 yes/confirmed, 👍 phase/yes

#446 Update to Volar 2.3
  .changeset/friendly-toes-rescue.md
  packages/language-server/index.js
  packages/language-server/package.json
  packages/language-server/test/completion.test.js
  packages/language-server/test/diagnostics.test.js
  packages/language-server/test/document-link.test.js
  packages/language-server/test/initialize.test.js
  packages/language-service/lib/commands.js
  packages/language-service/lib/language-plugin.js
  packages/language-service/lib/service-plugin.js
  packages/language-service/lib/virtual-code.js
  packages/language-service/package.json
  packages/language-service/test/language-plugin.js
  packages/language-service/tsconfig.json
  packages/typescript-plugin/index.cjs
  packages/typescript-plugin/package.json
  packages/vscode-mdx/package.json
  packages/vscode-mdx/src/extension.js
Labels: 🦋 type/enhancement, 📦 area/deps, 👶 semver/patch, 🙆 yes/confirmed, 👍 phase/yes

#450 Fix compatibility with TypeScript 5.5
  .changeset/cold-turtles-divide.md
  packages/language-service/lib/virtual-code.js
  packages/language-service/test/language-plugin.js
Labels: 🐛 type/bug, 🏡 area/internal, 👶 semver/patch, 🙆 yes/confirmed, 👍 phase/yes
