Repository mdx-js/mdx-analyzer, pull requests merged in 2024-05, with the labels that each got.

#431 Upgrade to Volar 2.2
  .changeset/red-timers-love.md
  packages/language-server/index.js
  packages/language-server/package.json
  packages/language-server/test/completion.test.js
  packages/language-server/test/diagnostics.test.js
  packages/language-server/test/document-link.test.js
  packages/language-server/test/initialize.test.js
  packages/language-service/lib/commands.js
  packages/language-service/lib/language-plugin.js
  packages/language-service/lib/service-plugin.js
  packages/language-service/package.json
  packages/language-service/test/language-module.js
  packages/typescript-plugin/package.json
  packages/vscode-mdx/package.json
Labels: 🤞 phase/open

#432 Only watch TS related file extensions if needed
  .changeset/hot-lies-wink.md
  packages/language-server/index.js
Labels: 🦋 type/enhancement, 🏁 area/perf, 👶 semver/patch, 👍 phase/yes

#437 Update to Volar services 0.0.45
  .changeset/spicy-tables-crash.md
  packages/language-server/package.json
Labels: 🦋 type/enhancement, 📦 area/deps, 👶 semver/patch, 🤞 phase/open

#440 Fix resolving MDX options from tsconfig.json
  .changeset/eighty-masks-matter.md
  packages/language-server/index.js
Labels: 🐛 type/bug, 🗄 area/interface, 👶 semver/patch, 👍 phase/yes
