Repository mdx-js/mdx-analyzer, pull requests merged in 2024-03, with the labels that each got.

#371 Migrate to TS Plugin
  .changeset/green-waves-travel.md
  .changeset/wicked-comics-sort.md
  packages/language-server/README.md
  packages/language-server/index.js
  packages/language-server/test/completion.test.js
  packages/language-server/test/definitions.test.js
  packages/language-server/test/diagnostics.test.js
  packages/language-server/test/document-link.test.js
  packages/language-server/test/document-symbols.test.js
  packages/language-server/test/folding-ranges.test.js
  packages/language-server/test/hover.test.js
  packages/language-server/test/initialize.test.js
  packages/language-server/test/no-tsconfig.test.js
  packages/language-server/test/prepare-rename.test.js
  packages/language-server/test/rename.test.js
  packages/vscode-mdx/.vscodeignore
  packages/vscode-mdx/package.json
  packages/vscode-mdx/script/build.mjs
  packages/vscode-mdx/src/extension.js
  packages/vscode-mdx/src/typescript-plugin.js
Labels: 🤞 phase/open

#410 Use @internal to mark internal APIs
  .changeset/afraid-snakes-agree.md
  .changeset/proud-trains-prove.md
  packages/language-service/lib/virtual-code.js
  packages/language-service/test/language-module.js
Labels: 🐛 type/bug, 🗄 area/interface, 👶 semver/patch, 👍 phase/yes

#416 Publish the TypeScript plugin as an npm package
  .changeset/curvy-cows-matter.md
  README.md
  packages/tsconfig.json
  packages/typescript-plugin/CHANGELOG.md
  packages/typescript-plugin/LICENSE
  packages/typescript-plugin/README.md
  packages/typescript-plugin/index.cjs
  packages/typescript-plugin/package.json
  packages/typescript-plugin/tsconfig.json
  packages/vscode-mdx/package.json
  packages/vscode-mdx/script/build.mjs
Labels: 🦋 type/enhancement, 🗄 area/interface, 🧒 semver/minor, 👍 phase/yes

#418 Add support for breakpoints
  .changeset/tiny-vans-protect.md
  fixtures/debug/example.mdx
  fixtures/debug/loader.mjs
  fixtures/debug/run.mjs
  fixtures/fixtures.code-workspace
  package.json
  packages/vscode-mdx/package.json
Labels: 🦋 type/enhancement, 🗄 area/interface, 👶 semver/patch, 👍 phase/yes

#419 Using syntax-only TS service plugin
  .changeset/fuzzy-poets-wonder.md
  packages/language-server/index.js
  packages/language-server/package.json
Labels: 👋 phase/new
